name: Build, Test and Deploy

on:
  push:
    branches:
      - main
env:
  JDBC_DATABASE: ${{ secrets.JDBC_DATABASE }}
  JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
  JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_PORT: ${{ secrets.IMAGE_PORT }}
  IMAGE_FILE: .tar

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with maven
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project
        run: |
          mvn -B -DskipTests clean install
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        run: |
          mvn test
  deploy:
    runs-on: ubuntu-22.04

    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and save Docker image
        run: |
          docker build -t $IMAGE_NAME \
            --build-arg JDBC_DATABASE=$JDBC_DATABASE \
            --build-arg JDBC_USERNAME=$JDBC_USERNAME \
            --build-arg JDBC_PASSWORD=$JDBC_PASSWORD \
            .
          docker save $IMAGE_NAME > ${IMAGE_NAME}${IMAGE_EXT}
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: $IMAGE_NAME
          path: ${IMAGE_NAME}${IMAGE_EXT}

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${IMAGE_NAME}${IMAGE_EXT}
          target: /root/containers/

      - name: Start new container using the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $IMAGE_NAME
            docker rm $IMAGE_NAME
            docker load < /root/containers/${IMAGE_NAME}${IMAGE_EXT}
            docker run -d --name $IMAGE_NAME -p $IMAGE_PORT:$IMAGE_PORT $IMAGE_NAME
            exit