name: Build, Test and Deploy

on:
  push:
    branches:
      - main
env:
  JDBC_DATABASE: ${{ secrets.JDBC_DATABASE }}
  JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
  JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with maven
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project
        run: |
          mvn -B -DskipTests clean install
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        run: |
          mvn test
  deploy:
    runs-on: ubuntu-22.04

    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and save Docker image
        run: |
          IMAGE_TAG=mads-backend-client
          docker build -t $IMAGE_TAG \
            --build-arg JDBC_DATABASE=$JDBC_DATABASE \
            --build-arg JDBC_USERNAME=$JDBC_USERNAME \
            --build-arg JDBC_PASSWORD=$JDBC_PASSWORD \
            .
          docker save $IMAGE_TAG > mads-backend-client.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: mads-backend-client
          path: mads-backend-client.tar

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: mads-backend-client.tar
          target: /root/containers/

      - name: Start new container using the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop mads-backend-client
            docker rm mads-backend-client
            docker load < /root/containers/mads-backend-client.tar
            docker run -d --name mads-backend-client -p 8080:8080 mads-backend-client
            exit